# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.

# to run with podman first execute podman pull k8s.gcr.io/pause:3.5
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lamp
  name: pod_lamp_host
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - apache2-foreground
    image: docker.io/mxmfrlv/php-apache:latest
    name: php8
    resources:
      limits:
        memory: "512Mi"
        ephemeral-storage: 1Gi
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: www-host-0
    - mountPath: /path_to/lamp_container/projects/
      name: projects-host-1
  hostNetwork: true
  volumes:
  - hostPath:
      path: ./www
      type: Directory
    name: www-host-0
  - hostPath:
      path: /path_to/lamp_container/projects
      type: Directory
    name: projects-host-1

